repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.4.2
    hooks:
      - id: isort
        args: [
          --line-length=100,
          --profile,
          "black",
        ]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.8
        args: [
            --line-length=100
        ]
