# Generated by Django 4.1.5 on 2023-01-10 15:28
import os

from django.contrib.auth import get_user_model
from django.db import migrations


def generate_superuser(apps, schema_editor):
    user_model = get_user_model()
    username = os.environ.get("DJANGO_SUPER_USER_USERNAME")
    email = os.environ.get("DJANGO_SUPER_USER_EMAIL")
    password = os.environ.get("DJANGO_SUPER_USER_PASSWORD")
    if not user_model.objects.filter(username=username, email=email).exists():

        admin = user_model.objects.create_superuser(
            username=username, password=password, email=email
        )
        admin.save()


def reverse_func(app, schema_editor):
    """Returns migration to the previous state"""

    user_model = get_user_model()
    username = os.environ.get("DJANGO_SUPER_USER_USERNAME")
    if user := user_model.objects.filter(username=username).exists():
        user.delete()


class Migration(migrations.Migration):
    dependencies = []
    operations = [migrations.RunPython(generate_superuser, reverse_func)]
