# Generated by Django 4.1.5 on 2023-01-11 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_budget_allowed_to_alter_budget_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="core.budget",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="core.transactioncategory",
            ),
        ),
    ]
