# Generated by Django 4.1.5 on 2023-01-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_transaction_budget_alter_transaction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="name",
            field=models.CharField(default="my budget", max_length=100),
            preserve_default=False,
        ),
    ]
